[[Bun]]
arch = "aarch64"
git-tree-sha1 = "8338b93c079ef74614bcf6d2b330761edea6fc73"
os = "macos"

    [[Bun.download]]
    sha256 = "e61ce4d3030834f8cdc272415f42cd61996504dfdc339b52cfbaadb86080d6a8"
    url = "https://github.com/JuliaBinaryWrappers/Bun_jll.jl/releases/download/Bun-v1.3.4+0/Bun.v1.3.4.aarch64-apple-darwin.tar.gz"
[[Bun]]
arch = "aarch64"
git-tree-sha1 = "1a533d6dd40602feaac99ea9e06da818dc2cef39"
libc = "glibc"
os = "linux"

    [[Bun.download]]
    sha256 = "f2b16dbdf0aeec901a9e9a0a0d970f0716118065d90e07090c4caae20ce5e533"
    url = "https://github.com/JuliaBinaryWrappers/Bun_jll.jl/releases/download/Bun-v1.3.4+0/Bun.v1.3.4.aarch64-linux-gnu.tar.gz"
[[Bun]]
arch = "aarch64"
git-tree-sha1 = "aff7f9acdc4ab3cb0c344b714472957b92c3c9aa"
libc = "musl"
os = "linux"

    [[Bun.download]]
    sha256 = "ee6caca1894ab799f33e943fca250d8c8b8a1b4e1bc8032a362439c5a2673307"
    url = "https://github.com/JuliaBinaryWrappers/Bun_jll.jl/releases/download/Bun-v1.3.4+0/Bun.v1.3.4.aarch64-linux-musl.tar.gz"
[[Bun]]
arch = "x86_64"
git-tree-sha1 = "2c60207d7a3d864cd2d1189ace5e406e640c3d20"
os = "macos"

    [[Bun.download]]
    sha256 = "703bdcf88fa7bfce5fba49fc82c7b24e9d854f7a8bd51f335b6147144800ed2f"
    url = "https://github.com/JuliaBinaryWrappers/Bun_jll.jl/releases/download/Bun-v1.3.4+0/Bun.v1.3.4.x86_64-apple-darwin.tar.gz"
[[Bun]]
arch = "x86_64"
git-tree-sha1 = "1d2c04f48d0f9ad2d00de2bd2bb0773d113d10cc"
libc = "glibc"
os = "linux"

    [[Bun.download]]
    sha256 = "dedb8c42092586f9a0c30ece3779c4b4463a801c9b2416924cf63c75f251d463"
    url = "https://github.com/JuliaBinaryWrappers/Bun_jll.jl/releases/download/Bun-v1.3.4+0/Bun.v1.3.4.x86_64-linux-gnu.tar.gz"
[[Bun]]
arch = "x86_64"
git-tree-sha1 = "ee5065590ab673a332cacc483da989100968c05c"
libc = "musl"
os = "linux"

    [[Bun.download]]
    sha256 = "8e34aca1eba91c521387559698064d86ac5fd9cc2c902b687bf794b488143710"
    url = "https://github.com/JuliaBinaryWrappers/Bun_jll.jl/releases/download/Bun-v1.3.4+0/Bun.v1.3.4.x86_64-linux-musl.tar.gz"
[[Bun]]
arch = "x86_64"
git-tree-sha1 = "62bd173d50d3c3bb22c93fb16be85f3c25c9434b"
os = "windows"

    [[Bun.download]]
    sha256 = "2014bf2ddedcb496daad024218e726d9104690736e4036243c2c43b17b828ce1"
    url = "https://github.com/JuliaBinaryWrappers/Bun_jll.jl/releases/download/Bun-v1.3.4+0/Bun.v1.3.4.x86_64-w64-mingw32.tar.gz"
